name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # tag tipo v0.1.0

permissions:
  id-token: write
  contents: read

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1